import java.util.HashMap;

class Solution {
    public boolean isIsomorphic(String s, String t) {
            if (s.length() != t.length()) {
                        return false;
                                }
                                        
                                                HashMap<Character, Character> sToT = new HashMap<>();
                                                        HashMap<Character, Character> tToS = new HashMap<>();
                                                                
                                                                        for (int i = 0; i < s.length(); i++) {
                                                                                    char sChar = s.charAt(i);
                                                                                                char tChar = t.charAt(i);
                                                                                                            
                                                                                                                        // Check if the mapping from s to t is consistent
                                                                                                                                    if (sToT.containsKey(sChar)) {
                                                                                                                                                    if (sToT.get(sChar) != tChar) {
                                                                                                                                                                        return false;
                                                                                                                                                                                        }
                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                    sToT.put(sChar, tChar);
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                        // Check if the mapping from t to s is consistent
                                                                                                                                                                                                                                                                    if (tToS.containsKey(tChar)) {
                                                                                                                                                                                                                                                                                    if (tToS.get(tChar) != sChar) {
                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                    tToS.put(tChar, sChar);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            